---
- name: Deploy MOTD
  hosts: production-server
  become: true
  tasks:
    - name: Check folder
      ansible.builtin.file:
        name: /etc/motd/
        state: directory
    - name: Déployer le message du jour
      copy:
        src: motd.j2
        dest: /etc/motd/
        mode: '744'
