---
- name: Deploy MOTD
  hosts: production-server
  become: true
  tasks:
    - name: Check folder
      ansible.builtin.file:
        name: /etc/motd
        state: absent

    - name: Déployer le message du jour
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root 