- name: Affichage des facts
  hosts: production-server
  tasks:
    - name: Afficher le hostname
      debug:
        msg: "La machine s'appelle {{ ansible_hostname }}"
    - name : afficher distrib et vers 
      debug :
        msg : "Distribution : {{ansible_distribution}} ; Version : {{ansible_distribution_version}}"
    - name : recup memeoire
      shell : | 
        cat /proc/meminfo | grep MemTotal
      register : memtotal

    - name : recup IP
      shell : |
        nmcli device show | grep IP4.ADDRESS | grep -v '127.' | head -n 1
      register : ip_add

    - name : afficher mem et IP 
      debug:
        msg : "Memoire totale : {{memtotal.stdout}} Adresse IP : {ip_add.stdout}}"
