---
- name: Déploiement Apache avec handler
  hosts: production-server
  become: true
  vars:
    file : httpd.conf
  tasks:
    - name: Installer httpd
      yum:
        name: httpd
        state: present
    - name: Déployer la configuration
      copy:
        src: {{file}}
        dest: /etc/httpd/conf/httpd.conf
        mode: '0644'
      notify: Redemarrer httpd
  handlers:
    - name: Redemarrer httpd
      service:
        name: httpd
        state: restarted
